services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: codxis_postgres
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=codxis
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5432:5432"
