services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: codxis_postgres
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=codxis
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
