services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: codxis_postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: codxis
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - '5432:5432'
